package store

import (
	"fmt"
	"testing"

	"gorm.io/gorm"

	"jianmen/internal/model"
	"jianmen/internal/storage"
)

func TestDebugDeleteAtNullSQL(t *testing.T) {
	db, _ := storage.Open(storage.Config{Driver: storage.DriverSQLite, DSN: ":memory:"})
	db.AutoMigrate(&model.DatabaseProvisioningOperation{}, &model.DatabaseAccount{})

	// Create test record  
	op := model.DatabaseProvisioningOperation{ID: "test-op", InstanceID: "inst-1", Kind: "create", ActorID: "actor-1", AdminAccountID: "adm-1", UpstreamUsername: "jm_test", Password: model.NewEncryptedField("x"), Host: "10.0.0.1", GrantsJSON: "[]", Stage: "drop_started", CleanupStatus: "in_progress", Revision: 3, LeaseOwner: "worker", LeaseToken: "lease", LeaseExpiresAt: timePtr(time.Now().Add(time.Hour))}
	if err := db.Create(&op).Error; err != nil {
		t.Fatal(err)
	}

	// Check the SQL generated by GORM for Updates with nil
	stmt := db.Session(&gorm.Session{DryRun: true}).Model(&model.DatabaseProvisioningOperation{}).
		Where("id = ? AND stage = ? AND revision = ?", "test-op", "drop_started", 3).
		Updates(map[string]interface{}{"deleted_at": nil})

	// SQL is in stmt.Statement.SQL
	sql := stmt.Statement.SQL.String()
	var vars []interface{}
	vars = stmt.Statement.Vars
	fmt.Printf("DryRun SQL: %s\n", sql)
	fmt.Printf("DryRun Vars: %v\n", vars)

	// Now actually try it
	result := db.Model(&model.DatabaseProvisioningOperation{}).
		Where("id = ? AND stage = ? AND revision = ?", "test-op", "drop_started", 3).
		Updates(map[string]interface{}{"deleted_at": nil})
	fmt.Printf("Actual: err=%v, rows=%d\n", result.Error, result.RowsAffected)

	var after model.DatabaseProvisioningOperation
	db.First(&after, "id = ?", "test-op")
	fmt.Printf("After: deleted_at=%v (nil=%v)\n", after.DeletedAt, after.DeletedAt == nil)

	// Check what was actually stored
	var raw *int
	db.Raw("SELECT deleted_at FROM database_provisioning_operations WHERE id = ?", "test-op").Scan(&raw)
	fmt.Printf("Raw value: %v (nil=%v)\n", raw, raw == nil)
}

func timePtr(t time.Time) *time.Time { return &t }
